# Generated by Django 3.0.5 on 2020-04-06 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("funds", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fund",
            name="band_1_rate",
            field=models.DecimalField(
                decimal_places=2, help_text="enter band one rate", max_digits=5
            ),
        ),
    ]
