# Generated by Django 3.0.5 on 2020-04-06 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("funds", "0002_auto_20200406_1723"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fund",
            name="band_1_lower",
            field=models.DecimalField(
                decimal_places=2, help_text="enter lower end of band one", max_digits=9
            ),
        ),
        migrations.AlterField(
            model_name="fund",
            name="band_1_rate",
            field=models.DecimalField(
                decimal_places=2, help_text="enter band one rate", max_digits=9
            ),
        ),
        migrations.AlterField(
            model_name="fund",
            name="band_1_upper",
            field=models.DecimalField(
                decimal_places=2, help_text="enter upper end of band one", max_digits=9
            ),
        ),
        migrations.AlterField(
            model_name="fund",
            name="fixed_costs_ongoing",
            field=models.DecimalField(
                decimal_places=2,
                help_text="enter fixed costs applied throughout year",
                max_digits=9,
            ),
        ),
        migrations.AlterField(
            model_name="fund",
            name="fixed_costs_year_start",
            field=models.DecimalField(
                decimal_places=2,
                help_text="enter fixed costs applied at year start",
                max_digits=9,
            ),
        ),
        migrations.AlterField(
            model_name="fund",
            name="setup_costs",
            field=models.DecimalField(
                decimal_places=2, help_text="enter yr 1 set-up  costs", max_digits=9
            ),
        ),
    ]
