# Generated by Django 3.0.5 on 2020-04-07 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("funds", "0003_auto_20200406_1732"),
    ]

    operations = [
        migrations.AddField(
            model_name="fund",
            name="band_2_lower",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="enter lower end of band two",
                max_digits=9,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="fund",
            name="band_2_rate",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="enter band two rate",
                max_digits=9,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="fund",
            name="band_2_upper",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="enter upper end of band two",
                max_digits=9,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="fund",
            name="band_3_lower",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="enter lower end of band three",
                max_digits=9,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="fund",
            name="band_3_rate",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="enter band three rate",
                max_digits=9,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="fund",
            name="band_3_upper",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="enter upper end of band three",
                max_digits=9,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="fund",
            name="band_4_lower",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="enter lower end of band four",
                max_digits=9,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="fund",
            name="band_4_rate",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="enter band four rate",
                max_digits=9,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="fund",
            name="band_4_upper",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="enter upper end of band four",
                max_digits=9,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="fund",
            name="band_5_lower",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="enter lower end of band five",
                max_digits=9,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="fund",
            name="band_5_rate",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="enter band five rate",
                max_digits=9,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="fund",
            name="band_5_upper",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="enter upper end of band five",
                max_digits=9,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="fund",
            name="band_6_lower",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="enter lower end of band six",
                max_digits=9,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="fund",
            name="band_6_rate",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="enter band six rate",
                max_digits=9,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="fund",
            name="band_6_upper",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="enter upper end of band six",
                max_digits=9,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="fund",
            name="fund_type",
            field=models.CharField(
                choices=[("p", "Pension Company"), ("f", "Fund Supermarket")],
                default="p",
                help_text="which type of fund",
                max_length=1,
            ),
        ),
        migrations.AddField(
            model_name="fund",
            name="platform_type",
            field=models.CharField(
                choices=[("itb", "ITB"), ("wf", "WF")],
                default="itb",
                help_text="which type of platform charges",
                max_length=3,
            ),
        ),
        migrations.AlterField(
            model_name="fund",
            name="band_1_lower",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="enter lower end of band one",
                max_digits=9,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="fund",
            name="band_1_rate",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="enter band one rate",
                max_digits=9,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="fund",
            name="band_1_upper",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="enter upper end of band one",
                max_digits=9,
                null=True,
            ),
        ),
    ]
