# Generated by Django 3.0.5 on 2020-04-08 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0004_auto_20200407_0719'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fund',
            old_name='band_1_upper',
            new_name='end_1_band_2',
        ),
        migrations.RenameField(
            model_name='fund',
            old_name='band_2_lower',
            new_name='end_2_band_3',
        ),
        migrations.RenameField(
            model_name='fund',
            old_name='band_2_upper',
            new_name='end_3_band_4',
        ),
        migrations.RenameField(
            model_name='fund',
            old_name='band_3_lower',
            new_name='end_4_band_5',
        ),
        migrations.RenameField(
            model_name='fund',
            old_name='band_3_upper',
            new_name='end_5_band_6',
        ),
        migrations.RemoveField(
            model_name='fund',
            name='band_4_lower',
        ),
        migrations.RemoveField(
            model_name='fund',
            name='band_4_upper',
        ),
        migrations.RemoveField(
            model_name='fund',
            name='band_5_lower',
        ),
        migrations.RemoveField(
            model_name='fund',
            name='band_5_upper',
        ),
        migrations.RemoveField(
            model_name='fund',
            name='band_6_lower',
        ),
        migrations.RemoveField(
            model_name='fund',
            name='band_6_upper',
        ),
        migrations.AlterField(
            model_name='fund',
            name='band_1_lower',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='enter lower end of band one', max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='fund',
            name='fixed_costs_ongoing',
            field=models.DecimalField(decimal_places=2, default=0, help_text='enter fixed costs applied throughout year', max_digits=9),
        ),
        migrations.AlterField(
            model_name='fund',
            name='fixed_costs_year_start',
            field=models.DecimalField(decimal_places=2, default=0, help_text='enter fixed costs applied at year start', max_digits=9),
        ),
        migrations.AlterField(
            model_name='fund',
            name='setup_costs',
            field=models.DecimalField(decimal_places=2, default=0, help_text='enter yr 1 set-up  costs', max_digits=9),
        ),
    ]
