# Generated by Django 3.0.5 on 2020-04-09 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0007_auto_20200409_1432'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fund',
            old_name='end_ç3_band_4',
            new_name='end_3_band_4',
        ),
    ]
