# Generated by Django 3.0.5 on 2020-04-14 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("funds", "0010_auto_20200414_0850"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fund",
            name="band_1_lower",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="fund",
            name="end_1_band_2",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="fund",
            name="end_2_band_3",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="fund",
            name="end_3_band_4",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="fund",
            name="end_4_band_5",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="fund",
            name="end_5_band_6",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
