# Generated by Django 3.0.5 on 2020-04-15 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0011_auto_20200414_0900'),
    ]

    operations = [
        migrations.AddField(
            model_name='fund',
            name='growth_type',
            field=models.CharField(choices=[('n', 'Normal'), ('s', 'Special')], default='n', max_length=1),
        ),
    ]
