# Generated by Django 3.0.5 on 2020-07-12 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0012_fund_growth_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fund',
            name='band_1_lower',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Band 1 start value (£)'),
        ),
        migrations.AlterField(
            model_name='fund',
            name='band_1_rate',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='BAND 1 RATE (%)'),
        ),
        migrations.AlterField(
            model_name='fund',
            name='band_2_rate',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='BAND 2 RATE (%)'),
        ),
        migrations.AlterField(
            model_name='fund',
            name='band_3_rate',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='BAND 3 RATE (%)'),
        ),
        migrations.AlterField(
            model_name='fund',
            name='band_4_rate',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='BAND 4 RATE (%)'),
        ),
        migrations.AlterField(
            model_name='fund',
            name='band_5_rate',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='BAND 5 RATE (%)'),
        ),
        migrations.AlterField(
            model_name='fund',
            name='band_6_rate',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='BAND 6 RATE (%)'),
        ),
        migrations.AlterField(
            model_name='fund',
            name='end_1_band_2',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Band 1 end value/Band 2 start (£)'),
        ),
        migrations.AlterField(
            model_name='fund',
            name='end_2_band_3',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Band 2 end value/Band 3 start (£)'),
        ),
        migrations.AlterField(
            model_name='fund',
            name='end_3_band_4',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Band 3 end value/Band 4 start (£)'),
        ),
        migrations.AlterField(
            model_name='fund',
            name='end_4_band_5',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Band 4 end value/Band 5 start (£)'),
        ),
        migrations.AlterField(
            model_name='fund',
            name='end_5_band_6',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Band 5 end value/Band 6 start (£)'),
        ),
    ]
